version: "1"

services:
  - type: web
    name: boimela-web-app
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /api/books
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d78k8sua2pns73drdm6g-a/boimela
      - key: DB_USER
        value: boimela_user
      - key: DB_PASS
        value: 99p7BHi5yY32b8XsGjLdElVzDOGhW9J5
      - key: PORT
        value: '8080'
