spring:
  application:
    name: boimela

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/boimela_db}
    username: ${DB_USER:boimela_user}
    password: ${DB_PASSWORD:boimela_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
